### ISSUE TITLE
how to get struct fields value?

### ISSUE THREAD

**Issue by adminSxs** [TedDriggs/darling#100]
example
```rust
#[macro_use]
extern crate validator_derive;

fn main() {
    // println!("{}","some_string".to_pascal_case());
    let info: UserInfo = Default::default();
    // info.name();
    println!("email={:#?}",info.get_name());
    println!("phone={:#?}",info.get_phone());
}

#[derive(Debug,Validator)]
struct UserInfo{
    #[validate(email)]
    name: String,
    phone: String

}
impl Default for UserInfo{
    fn default() -> Self {
        UserInfo{
            name: String::from("test@test.com"),
            phone: String::from("123456")
        }
    }
}

```
i want to by call get_name method get name is test@test.com,get_phone is  123456

**Comment by TedDriggs** [comment]
This crate isn't `validator_derive`, so I'm not sure I understand the question here. Could you clarify?

**Comment by cjburkey01** [comment]
> This crate isn't `validator_derive`, so I'm not sure I understand the question here. Could you clarify?

I'm not sure but it seems like a case of asking the wrong people for something? They may have been asking for an example of how to get darling to automatically generate some of those methods for them to make it less verbose, but I'm not exactly how they meant that if they did
