### ISSUE TITLE
Auto-populated field `FromField::ident` is `Option<syn::Ident>`

### ISSUE THREAD

**Issue by casey** [TedDriggs/darling#102]
I'm not sure about this, because I'm just getting started with `darling`. (Thank you for writing it, by the way!)

Should the `FromField::ident` actually be `Option<syn::Ident>`, because it might be the field of tuple struct? If so I think the [docs](https://github.com/TedDriggs/darling/blob/7615326025038c7f461f21705a5d6d494132faa4/src/lib.rs#L46) are incorrect.

**Comment by TedDriggs** [comment]
I think you're correct.
