### ISSUE TITLE
Support for enum variant discriminant

### ISSUE THREAD

**Issue by katyo** [TedDriggs/darling#104]
As I see currently `FromVariant` derive macro has missing support for [discriminant](https://docs.rs/syn/1.0.54/syn/struct.Variant.html#structfield.discriminant) part of enum variants.
I think it will be good to support it too.

**Comment by TedDriggs** [comment]
I've put up a PR for it; please take a look and let me know if it solves your use-case.

**Comment by katyo** [comment]
LGTM.
I tested this feature in [rquickjs#12](/DelSkayn/rquickjs/pull/12).
Works complettely as expected.

**Comment by TedDriggs** [comment]
Excellent. I'll push out a new version tomorrow morning.

**Comment by katyo** [comment]
@TedDriggs Great thanks for super fast support!

**Comment by TedDriggs** [comment]
Done.
