### ISSUE TITLE
Possible to parse different types?

### ISSUE THREAD

**Issue by sharksforarms** [TedDriggs/darling#106]
For example, I'd like to be able to parse the following:

```rust
// path: LitStr
#[your_attr(path = "hello")]
fn do_stuff() {
}
```

or

```rust
// path: LitByteStr
#[your_attr(path = b"hello_as_bytes")]
fn do_stuff() {
}
```

**Comment by sharksforarms** [comment]
I realized I can impl FromMeta on an enum and do it that way!

**Comment by TedDriggs** [comment]
Ah, you found the answer 2 minutes before I responded!

An enum is the best way to do it. 

For the curious, there are two alternatives:
1. Implement `FromMeta` manually on a custom type providing a `from_value` body
2. The deriving struct could accept `syn::Lit` and then do the validation after darling's work is complete.
