### ISSUE TITLE
Semver breakage in latest release

### ISSUE THREAD

**Issue by sharksforarms** [TedDriggs/darling#107]
Hey @TedDriggs, semver breakage happens, this is a hard thing to keep track of and I've made the mistake many times.

Not sure how far reaching this is, but one thing that could be done is yank the release from crates.io and re-release with a 0.11.0 release.

If not, every depending library which uses darling (which don't specify exact versions) will need to re-release.

**Comment by TedDriggs** [comment]
On it.

**Comment by TedDriggs** [comment]
Travis is taking a long time to check this one, not sure why.

**Comment by TedDriggs** [comment]
Done.

**Comment by sharksforarms** [comment]
Thanks!
