### ISSUE TITLE
Is there any way to support "positional" args?

### ISSUE THREAD

**Issue by mcronce** [TedDriggs/darling#109]
I've been Googling, hunting through docs, and reading `darling` code but haven't tried just throwing anything at the wall to see if it works yet :)

What I'm trying to achieve is something along these lines:
```rust
#[my_macro(value1, arg2 = "value2")]
struct MyStruct { ... }
```

Is this (currently) possible using `darling`?

The specific use case is that I'm trying to add support for associated consts to `enum_derive`, without breaking backward compatibility - right now `enum_derive` works as follows:
```rust
#[enum_derive]
trait MyTrait { ... }

#[enum_derive(MyTrait)]
enum MyEnum { ... }
```

The way I'm imagining my PR working is something like this:
```rust
#[enum_derive]
trait MyTrait {
    const value: u8;
    ...
}

#[enum_derive(MyTrait, value = 0)]
enum MyEnum { ... }
```

**Comment by TedDriggs** [comment]
This should be possible, albeit with some custom implementation. I'd suggest trying to make a struct something like this:

```rust
struct MagicFirst<T> {
    references: syn::Path,
    fields: T,
}

impl FromMeta for MagicFirst<T: FromMeta> {
    // ...
}
```

In the `FromMeta` impl, slice off the first argument, then pass the rest of the nested meta items to `T::from_list` so they can be handled normally by `darling`.
