### ISSUE TITLE
Update to 2018 Edition

### ISSUE THREAD

**Issue by TedDriggs** [TedDriggs/darling#127]
Per [this comment](https://github.com/TedDriggs/darling/issues/125#issuecomment-8124978300), `darling` can move to the 2018 edition, and code it emits will be treated according to those rules even if the calling crate is on 2015 Rust.

Staying on 2015 is going to make contribution to `darling` harder over time, and the migration will probably get harder over time. However, the migration is going to be hard due to lack of a test plan.

- [x] Migrate all code _outside_ `quote` macros
- [x] Migrate code _inside_ `quote` macros
- [x] Test from a crate that is still on 2015

This should probably be a minor version bump.

**Comment by TedDriggs** [comment]
@kangalioo 79 files changed later, I think this is ready to go. Planning to roll one more change in and to then call it `0.13.0-beta`

**Comment by kangalioo** [comment]
Wow, I wasn't aware you were already hard at work on this! Really cool, thank you!
