### ISSUE TITLE
More types of attributes needed

### ISSUE THREAD

**Issue by tailhook** [TedDriggs/darling#134]
1. I'd like to have `FromMeta for syn::Expr`. Rust supports not only string/int/ident attributes, but arbitrary expressions, like `#[clap(version=clap::crate_version!())]`. Currently darling says `Unable to parse attribute: expected literal`. And I think we need to change trait API to fix that.
2. I want to parse `doc` attribute too. E.g. `clap` uses docstrings as the description of the options. `///`-style comments are formatted as `doc=` in complier, so currently darling fails with `Name-value arguments are not supported. Use #[doc(...)]`

Do you think these would be worthy additions to the crate? Or were these limitations intentional?

**Comment by TedDriggs** [comment]
The `FromMeta` trait relies on `syn::Meta`, which is more restrictive than the current attribute grammar. `darling` relies on the more restrictive grammar to be able to perform its declarative parsing and error tracking.

`syn` already exposes the `Parse` trait for implementing custom input parsing; I don't think there's enough regularity to the new expanded grammar for `darling` to easily work with it.

---

For `doc` attribute, use `#[darling(forward_attrs(doc))]` to get the full attribute, where you can then do the extraction of the doc string yourself.

**Comment by jvail** [comment]
I suppose my question is related to this one. I am pretty new to rust and therefor most likely do not fully understand darlings api. However, here is my question:  I have an attribute macro with a range of attributes & values like this

```rust
#[my_macro(attr_int=1, attr_str="a_str")]
fn some_functio() {}
```
So far so good. I wonder if there is a way to pass a struct without getting the "expect literal" error mentioned above. Something like this:

```rust
struct SomeStruct { a: String } 

#[my_macro(attr_struct=SomeStruct { a: "A" })]
fn some_functio() {}
```

I went through the examples but it seems this might not work with attribute macros - or I struggle to understand how. Any hints welcome!

Thank you

**Comment by TedDriggs** [comment]
In general, the way to do that would be to have the caller pass the path to a function that returns the desired struct, e.g.

```rust
fn make_struct() -> SomeStruct {
    SomeStruct { a: "A".into() }
}

#[my_macro(attr_thing = "make_struct")]
fn some_function() {}
```

**Comment by jvail** [comment]
Thank you, but isn't that essentially the same as doing

```rust
struct SomeStruct { a: String }
impl Default for SomeStruct { ... }

#[my_macro(attr_thing = "SomeStruct")]
fn some_function() {}

// inside the marco code

quote! { 
  let thing = #attr_thing:: default()
}
```

I am looking for a way pass some nested "things". In the example the value of the field "a".
