### ISSUE TITLE
Clarify origin of `MyTrait` name

### ISSUE THREAD

**Issue by hohav** [TedDriggs/darling#135]
I'm still trying to wrap my head around darling, so apologies if these are dumb questions.

The name `MyTrait` is used in the main README example, but never defined. Based on `examples/consume_fields.rs` example I'm guessing darling is supposed to generate that name by CamelCasing `my_trait` in `#[darling(attributes(my_trait))]`. Assuming that's correct, I have three issues/questions:

1. Is this documented anywhere?
2. Is `attributes(my_crate)` in the README supposed to be `my_trait`?
3. When I copy `consume_fields.rs` into my own test crate, its `main` fn works; but when I try to put the same code in an integration test I get "cannot find derive macro `MyTrait` in this scope", despite `use my_crate::*`. What am I missing?

**Comment by TedDriggs** [comment]
Good catch; that's not made explicit in the documentation.

You'd specify `MyTrait` in your `lib.rs` file where you export the proc macro itself. [**Here's**](https://github.com/TedDriggs/from_variants/blob/master/from_variants_impl/src/lib.rs#L12) an example from a real crate that uses `darling`.

**Comment by hohav** [comment]
Ah, thank you. I was misled by the fact that the main fn in `consume_fields.rs` works without any declaration of `MyTrait`, but I guess that's because it's only running the macro and not actually compiling past that.
