### ISSUE TITLE
Allow FromStr types

### ISSUE THREAD

**Issue by birkenfeld** [TedDriggs/darling#14]
I'd propose to allow e.g. `Result<i32, darling::Error>` in the struct.

I'll submit a patch if you think this is a useful idea.

**Comment by TedDriggs** [comment]
I don't think your exact suggestion is possible without specialization, but if you can make it work I'd be happy to review a PR for it.

A much simpler approach would be adding thin `FromMetaItem` impls for the types you care about, wrapping their `FromStr` impls. Those would go in [core/src/from_meta_item.rs].

With those in place, the existing blanket `impl FromMetaItem<T> for Result<T>` would cover the case you're describing.

**Comment by TedDriggs** [comment]
@birkenfeld I've shipped v0.2.1, which has these impls added.

**Comment by birkenfeld** [comment]
Sorry for not replying earlier. This is nice, thank you - I'll get back to you if I need `FromMetaItem` implemented for other types as well.
