### ISSUE TITLE
How to parse types?

### ISSUE THREAD

**Issue by Bajix** [TedDriggs/darling#140]
I'd like to be able to pass in a type handler via an attribute but it's not obvious how to do so.

```
#[derive(Loadable)]
#[data_loader(handler = DieselHandler<FooLoader>)]
```

Ideally something like this would work, however I get the error:

> the trait bound `syn::Type: FromMeta` is not satisfied
the trait `FromMeta` is not implemented for `syn::Type`

```
#[derive(Debug, FromDeriveInput)]
#[darling(attributes(data_loader))]
struct LoadByArgs {
  #[darling(default)]
  internal: bool,
  handler: syn::Type,
}

#[proc_macro_derive(Loadable, attributes(data_loader))]
pub fn load_by(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
  let input = parse_macro_input!(input as DeriveInput);

  let LoadByArgs {
    internal, handler
  } = FromDeriveInput::from_derive_input(&input).expect("can't parse attribute");

  let expanded = quote! {
      ...
  };

  proc_macro::TokenStream::from(expanded)
}
```

**Comment by Bajix** [comment]
I used `syn::Path` [here](https://github.com/Bajix/deque-loader-rs/commit/b533ab35897fd48ed3ad7ab35c93e9f7dfc2adde) as a way to unblock this, but ideally I'd like to drop the quotes.

**Comment by TedDriggs** [comment]
You need to use quotation marks around items in that position if you want to use `darling`; otherwise it's technically not a valid meta-item. This is the same as `syn` and other crates. Given the amount of work needed to rebuild `darling` to allow this, it's unlikely to be done.

**Comment by Bajix** [comment]
I see. What about using a syntax more like Diesel’s ‘#[belongs_to(User)]’? That’s also not viable?

**Comment by TedDriggs** [comment]
That particular pattern is covered by [`darling::util::PathList`](https://docs.rs/darling/0.13.0/darling/util/struct.PathList.html). The limitation comes with what is after the = sign, and is imposed by `syn`, the library `darling` uses for its AST parsing.

**Comment by Bajix** [comment]
Do you have an example of this that you could refer to? I tried doing a Github search for projects using PathList but I couldn't find any examples doing this. 

I thought [this](https://github.com/Bajix/deque-loader-rs/blob/main/deque-loader-derive/src/lib.rs#L13) could be rewritten as so but this doesn't work as FromDeriveInput isn't implemented for darling::util::PathList. 

```
#[derive(Debug, FromDeriveInput)]
#[darling(attributes(data_loader))]
struct LoaderArgs {
  #[darling(multiple)]
  handler: Vec<syn::Path>,
}
...
#[derive(Debug, FromDeriveInput)]
#[darling(attributes(data_loader))]
struct LoaderArgs (
  #[darling(multiple)]
  Vec<darling::util::PathList>
)
```

I just thinking that syntactically #[data_loader(DieselHandler<UserLoader>)] is more preferable to #[data_loader(handler = "DieselHandler<UserLoader>")] as the former will suggest imports in an IDE and the later will not. I probably just need to thoroughly read over syn/quote/darling... Rust has a way of making you think over a lot of things 🤯
