### ISSUE TITLE
How to get the value of the derive attribute?

### ISSUE THREAD

**Issue by jhoobergs** [TedDriggs/darling#147]
I'm trying to get the derive attribute for the struct / enum that derive my proc macro, but I can't  seem to get it.

I'm using `FromDeriveInput` with `#[darling(forward_attrs)]` (to get all attributes) and the `attrs` field does not contain the derive attributes. Well, actually it is always empty, so doc strings aren't forwarded either.

I looked in the examples and tests folder, but none of them use the `forward_attrs`.

**Comment by jhoobergs** [comment]
Ok, It seems I can only get comments and derives that are written below the `#[derive(MyTrait)] ` line.

**Comment by pkolaczk** [comment]
I'm having a similar problem. The documentation and examples mention many features without actually explaining what they do and how they work together. 

I'm trying to get access to all attributes on a fields:
```rust
#[derive(Debug, FromField)]
#[darling(attributes(my_attr), forward_attrs)]   // I tried many combinations of this, e.g. `forward_attrs(my_attr)`
struct UdtField {
    ident: Option<syn::Ident>,
    ty: syn::Type,
    attrs: Vec<syn::Attribute>
}

#[derive(Debug, FromDeriveInput)]
#[darling(supports(struct_named))]
struct Udt {
    ident: syn::Ident,
    data: ast::Data<util::Ignored, UdtField>,
}

```

Yet when I put an attribute #[my_attr] on a field like this:

```rust
#[derive(MyTrait)]
struct Address {
    #[my_attr]
    street: String,
    number: i64
}
```

I'm getting an error:
```
error: cannot find attribute `my_attr` in this scope
```
