### ISSUE TITLE
build failed error: could not compile `darling_core`

### ISSUE THREAD

**Issue by DuckEater54** [TedDriggs/darling#149]
I'm currently working with rg3d but every time I attempt to build my project it gives an error saying that darling_core could not be compiled.
![image](https://user-images.githubusercontent.com/86613052/134773955-bbcabe28-66b0-4e02-96a7-b97a61ef48b1.png)

**Comment by DuckEater54** [comment]
> error: couldn't read C:\Users\budgi\.cargo\registry\src\github.com-1ecc6299db9ec823\darling_core-0.13.0\src\codegen\default_expr.rs: stream did not contain valid UTF-8
>  --> C:\Users\budgi\.cargo\registry\src\github.com-1ecc6299db9ec823\darling_core-0.13.0\src\codegen\mod.rs:2:1
>   |
> 2 | mod default_expr;
>   | ^^^^^^^^^^^^^^^^^
> 
> error: could not compile `darling_core` due to previous error
> warning: build failed, waiting for other jobs to finish...
> error: build failed

**Comment by TedDriggs** [comment]
Hmm; I'm not seeing that issue on CI. Does it still repro for you?

**Comment by DuckEater54** [comment]
No it doesnt, its fixed now.

**Comment by DuckEater54** [comment]
And I'm back with a new problem that may be obvious but I'm oblivious

> **error**: failed to download `darling_fore v0.13.0`
> Caused by:
>    failed to get packages from source
> Caused by:
>    failed to unpack package `darling_core v0.13.0`
> Caused by:
>    failed to iterate over archive
> Caused by:
>     Invalid gzip jeader

**Comment by DuckEater54** [comment]
I forgot to mention I'm using cargo 1.57.0-beta
