### ISSUE TITLE
Read Vec<syn::Attribute>

### ISSUE THREAD

**Issue by swfsql** [TedDriggs/darling#150]
I'm trying to structurize some attribute args burried inside of an attribute proc-macro, like so:

```rust
#[my_proc_macro]
trait MyTrait<T> {
  #[my_proc_macro(some_settings = "my_setting")]
  const C: T;
  #[my_proc_macro(more_settings = "other settings")]
  fn f();
  // ...
}
```

Would you know the recommended way of doing this?  
At first, when on the function:
```rust
#[proc_macro_attribute]
pub fn my_proc_macro(attr: TokenStream, item: TokenStream) -> TokenStream {}
```
I can use `attr` with darling, but after I do some parsing on `item`, which then becomes eg. `syn::ItemTrait`, which has the `attrs: Vec<syn::Attribute>` field, I couldn't find a way of using that `attrs` with darling anymore (in order to have structures to represent the args on various kinds of items).  
Would you have an example of this? I looked around but didn't quite find any. This likely can be the case that I'm missing some point about proc-macros/syn/darling.

ps. the trait was an example, but I'm actually also trying to be able to apply the same `my_proc_macro` on `impl trait for Struct {}` items, and so on..

Thanks in advance!

**Comment by TedDriggs** [comment]
I'm planning to introduce a new attribute for this use-case; see #151 for the details of the proposal.
