### ISSUE TITLE
Detailed Examples

### ISSUE THREAD

**Issue by glademiller** [TedDriggs/darling#17]
I love where this project is going and I would be surprised if it wasn't already on your radar but a good examples directory would be excellent. 

The main issue I faced yesterday when trying to use darling was getting the example in the Readme compiling I had to implement a trait by hand in order for it to work which wasn't in the example.

Once I got that working it is a bit of work to figure out how to setup something in a struct to get be able to derive data about the fields on a struct. Similar to how serde allows you to annotate each field. I think a few good examples would go a long way to making darling easily usable.

**Comment by TedDriggs** [comment]
I've picked up the project for the first time in a few months, and I definitely agree there's room for some better examples.

> The main issue I faced yesterday when trying to use darling was getting the example in the Readme compiling I had to implement a trait by hand in order for it to work which wasn't in the example.

That's... concerning. I'll look into that.

**Comment by TedDriggs** [comment]
@glademiller I've added one example, though I haven't had time to test it in depth.

**Comment by glademiller** [comment]
Great! Thanks for the quick reply. I'll take a close look this evening.

**Comment by TedDriggs** [comment]
I've now added a second example, and found a way to make the examples produce something useful when they're run.

**Comment by glademiller** [comment]
These are excellent. Thank you for taking the time to get this done. I have something I want to build and this will help a lot. From my perspective you met my expectations for this issue and it could be closed unless you want to use it as a jumping off point for further examples.
