### ISSUE TITLE
How to write repeated field

### ISSUE THREAD

**Issue by depth-liu** [TedDriggs/darling#189]
Hi,

I want write a field like serde alias, it can be repeated and will collected as a Vec.
How to write it using darling?

```rust
struct Data {
  #[serde(alias = "name")] 
  #[serde(alias = "name1")] 
  q2: String,
}
```

I have tried, and darling reported error like this:

```
error: Duplicate field `alias ` at q2
```

**Comment by TedDriggs** [comment]
Have you tried using `#[darling(multiple)]`?

**Comment by depth-liu** [comment]
@TedDriggs thanks, I will.
