### ISSUE TITLE
Syn 0.12

### ISSUE THREAD

**Issue by Palmik** [TedDriggs/darling#19]
The crate currently does not work with the new syn 0.12

**Comment by Eijebong** [comment]
@Palmik I have a patch there, https://github.com/Eijebong/darling/commit/11872ebc884a7249c598fc904312e57dc9bbcda5 it compiles and tests are passing but there are some things in there I dislike, I'll try to finish it tomorrow and open a PR

**Comment by TedDriggs** [comment]
@Eijebong thanks! I was going to start on this, but I'll wait for your PR. If you put it up now I can help with the tests.

**Comment by Eijebong** [comment]
Fixed the tests, it was a bug in syn (https://github.com/dtolnay/syn/pull/347)
Going to open the PR now :)

**Comment by TedDriggs** [comment]
Fixed by @Eijebong in #20
