### ISSUE TITLE
Implement FromMeta::from_word() when deriving

### ISSUE THREAD

**Issue by exactly-one-kas** [TedDriggs/darling#191]
I would like to be able to use derived `FromMeta` implementations on attributes without parentheses (as long as the struct also implements `Default`)

This is my proposal for the API:

```rust
#[derive(Default, FromMeta)]
#[darling(allow_word)]
struct MyCoolAttr {
    pub param1: String,
}
```

```rust
#[derive(AwesomeTraitGoodJob)]
struct StructForTheMasses {
    #[my_cool_attr]
    field1: String,
    #[my_cool_attr(param1 = "yes")]
    field2: String,
}
```

If this is fine, I can implement it and make a PR for that

**Comment by TedDriggs** [comment]
Unfortunately, I think this would have significant adverse impacts: darling merges all attributes of the same path, so there’s not a good way to differentiate that case from the pathless case.

**Comment by exactly-one-kas** [comment]
I'm not sure I understand attribute merging correctly, are the following two equivalent?
`#[my_cool_attr(param1 = "a value", param2 = "another value")]` and `#[my_cool_attr(param1 = "a value"), my_cool_attr(param2 = "another value")]`

In any case, would treating `#[my_cool_attr]` as `#[my_cool_attr()]` suffice?

**Comment by TedDriggs** [comment]
You are correct about the equivalency. The problem right now is that there's no difference between the absence of a field-level attribute and the `#[my_cool_attr()]`; because `darling` only really cares about what's inside the parentheses (unless `forward_attrs` is set), the empty attribute has nothing for `darling` to see or interact with.

**Comment by TedDriggs** [comment]
If there was a way to do this, it'd lie somewhere in the "outer impls" - `FromField`, `FromVariant`, `FromDeriveInput`, etc. Those are the traits responsible for getting attributes to drive `FromMeta`, so they might be able to (handwaving ensues) note whether or not they saw any attributes of a particular path.

**Comment by exactly-one-kas** [comment]
How about the following:

```rust
Data::Struct(ref data) => {
    let inits = data.fields.iter().map(Field::as_initializer);
    let declare_errors = base.declare_errors();
    let require_fields = base.require_fields();
    let check_errors = base.check_errors();
    let decls = base.local_declarations();
    let core_loop = base.core_loop();
    let default = base.fallback_decl();
    let post_transform = base.post_transform_call();

    let from_word_impl = if base.allow_word {
        Some(quote!(
            fn from_word() -> ::darling::Result<Self> {
                Self::from_list(&[])
            }
        ))
    } else {
        None
    };

    quote!(
        #from_word_impl

        fn from_list(__items: &[::syn::NestedMeta]) -> ::darling::Result<Self> {

            #decls

            #declare_errors

            #core_loop

            #require_fields

            #check_errors

            #default

            ::darling::export::Ok(Self {
                #(#inits),*
            }) #post_transform
        }
    )
}
```

Would this work or is this too hacky?

**Comment by TedDriggs** [comment]
Isn't that changing the `FromMeta` derivation?

**Comment by exactly-one-kas** [comment]
only by opt-in using `#[darling(allow_word)]`, so it would be fully backwards-compatible while still allowing merging with other attribute instances

**Comment by TedDriggs** [comment]
Hold on, I think I was misunderstanding your idea. I'd suggest taking a look at the poorly-named [`darling::util::Override`](https://docs.rs/darling/latest/darling/util/enum.Override.html), which provides a non-proc-macro way of achieving what you've described.

**Comment by exactly-one-kas** [comment]
Yes, that works great, thanks for your help!

**Comment by TedDriggs** [comment]
I am very open to suggestions for a better name for that enum - this isn't the first time people have been unable to find the functionality because the name is very non-obvious.

**Comment by exactly-one-kas** [comment]
I made a similar wrapper that I called `FromMetaWord`

Alternatively, how about `MaybeBare`?
