### ISSUE TITLE
FromMeta parsing doesn't error on unrecognized literals in attribute list

### ISSUE THREAD

**Issue by leighmcculloch** [TedDriggs/darling#192]
FromMeta doesn't error in all cases that unexpected tokens end up in the attribute list.

It doesn't error in the case that a string literal is in the attribute list. For example:
```rust
#[myattribute(myfield = "export", "randomliteral")]
```

Parsing the attribute list will error if it sees a field that is anticipated, but not for `"randomliteral"` which it will ignore.

cc @jonjove

**Comment by leighmcculloch** [comment]
Hmm, on inspection of the code I'm not sure why an error isn't being seen in this case. For example, the following code is triggered on the attribute args list being a string literal and returns an error:
https://github.com/TedDriggs/darling/blob/b71b23e59c9522dbb5b9408c3419d3ab000bbaf8/core/src/from_meta.rs#L130-L134

**Comment by leighmcculloch** [comment]
Maybe this block of generated code in the macro is the issue, since it ignores metas that are of the literal type:
https://github.com/TedDriggs/darling/blob/dbdcd93d0e78d3078f5fe148f7824fe1fe310368/core/src/codegen/variant_data.rs#L60-L68

**Comment by leighmcculloch** [comment]
@TedDriggs I've opened a fix for this issue in https://github.com/TedDriggs/darling/pull/193.

**Comment by casey** [comment]
Just wanted to mention that I ran into this. I was trying to parse something like this:

```
#[derive(MyTrait)]
#[my_trait("foo")]
struct Foo {
}
``

Which was not working, but which wasn't throwing an error, I think because the literal "foo" was being ignored.
