### ISSUE TITLE
Possible to parse single attribute value without key?

### ISSUE THREAD

**Issue by casey** [TedDriggs/darling#196]
Okay, editing this comment many times, as I figure out what I'm not getting. I'd like to be able to parse this:

```
#[derive(Foo)]
#[foo("bar")]
struct Foo {
}
```

I looked at the existing examples but had a hard time figuring this out.

Is this supported, or do I have to this:

```
#[derive(Foo)]
#[foo(key = "bar")]
struct Foo {
}
```

**Comment by TedDriggs** [comment]
`darling`'s derived impls don't support positional arguments - they require items to be key-value or key-list pairs, with key-list pairs being treated as sets, like in the case of `#[derive(LIST_THAT_IS_A_SET_HERE)]`.

It is possible to manually implement `FromMeta` if you want to use positionals with key-value options. The reason behind the lack of support in derived impls, and the path to a manual impl, are discussed in #195.
