### ISSUE TITLE
Get Each Field Attributes

### ISSUE THREAD

**Issue by vahidjavaherifar** [TedDriggs/darling#198]
Hi,

Considering this code:

```
#[derive(MyMacro)]
struct Point {
    #[myattr(test1(arg1 = 0, arg2 = 10))]
    x: u8,
    #[myattr(test2(arg1 = "Hello, World!")]
    y: u8,
}
```

How can I get each field attributes when iterating over fields and map to a struct deriving from darling traits?

**Comment by TedDriggs** [comment]
So I think what you're trying to achieve is `#[myattr(TEST_NAME(ARGS*))]`, right? The test names are dynamic, and the args are a sequence of expressions?

**Comment by TedDriggs** [comment]
You won't get much from `darling`'s derived impls here. While there is support for parsing into a `HashMap`, I don't think that would work at the top-level of a field's attribute as we're seeing here; it might work if the input was `#[myattr(tests(test1(...)))]`, but that isn't what you're after.

Moreover, it seems like you'd want each occurrence of your attribute to be its own invocation and to not have them be merged together - the merging is a behavior that `darling` enables by default and doesn't provide a means to disable, as it's closer to how standard attributes such as `derive` and `allow` work.

If you do go the `syn` path, you would be able to drop the `arg0`, and `arg1` notation in favor of having an expression list directly in the body of the arguments.
