### ISSUE TITLE
`FromVariant` derive has incorrect type on `fields` field

### ISSUE THREAD

**Issue by mfreeborn** [TedDriggs/darling#200]
Looking at the documentation [here](https://docs.rs/darling/latest/darling/#fromvariant), it suggests that the type for the `fields` field is `Option<darling::ast::Fields<__>>`.

Having just tried to implement this (using `darling` v0.14.1), I get an error stating that the true type is actually `darling::ast::Fields<_>`.

Testing it on a plain enum without tuple/field variants, `fields` returns an empty vector. I think it would be better if the behaviour was as per the documentation, and that non-tuple/field variants return `None` and others return `Some(*at least one field*)`.

I also think it would be clear in the docs to mention that `darling::ast::Fields<_>` something which implements FromField e.g. `darling::ast::Fields<T: impl darling::FromField>` just to save a bit of digging around in the documentation/chasing error messages.

**Comment by TedDriggs** [comment]
Changing it to be an `Option` would break lots of existing code, so I'll update the docs to accurately capture the true type.

**Comment by mfreeborn** [comment]
That's much clearer, thanks!
