### ISSUE TITLE
How do I specify spans/use SpannedValue precisely?

### ISSUE THREAD

**Issue by detly** [TedDriggs/darling#212]
I'm trying to use Darling to write some derive proc macros under Rust stable 1.65, and I'd like to improve the spans I'm using for my errors.

The code extracts I show below are all from a [sample project](https://gitlab.com/detly/darling-test), if it helps. Basically I have:

```rust
#[derive(Debug, FromDeriveInput)]
struct DarlingTestDerive {
    ident: Ident,
    generics: Generics,
    data: darling::ast::Data<(), ()>,
}
```

(In real code the second `()` would be some other Darling-derived type eg. a `FromField` derived type.)

In my derive macro code, I'd like to be able to specify two different spans for two different error cases:

1. The span for `struct|enum` ie. the "type" of `Data`.
2. The span for the `Data` itself eg. all the fields of a struct.

Unfortunately not only can I not figure out how to do this, I seem to be able to only get a span covering a doc comment two lines before my data type.

For example, if I simply take the span for the input

```rust
let input = parse_macro_input!(input as syn::DeriveInput);
let span = input.span();
// ...
Err(syn::Error::new(span, "these fields are bad"))
```

...then for the using code:

```rust
/// Some doc comment.
#[derive(Clone, Debug, Default, DarlingTest, PartialEq)]
struct DarlingTestStruct(#[darling_test] bool, usize);
```

...it is *the doc comment* that is highlighted.

```text
error: these fields are bad
 --> tests/test.rs:5:5
  |
5 |     /// Some doc comment.
  |     ^^^^^^^^^^^^^^^^^^^^^
```

I can't figure out (a) if this is a problem I should solve with tools in Darling or in Syn and (b) whichever it is, how to do it.

It's not in the Rustdocs, but the repository readme says:

> Use `darling::util::SpannedValue` in a struct to get access to that meta item's source code span. This can be used to emit warnings that point at a specific field from your proc macro.

The type's docs say:

> You can use a `SpannedValue<T>` as a field in any struct that implements or derives any of darling’s core traits.

I couldn't figure out how to apply this though. I thought maybe wrapping the field of interest in it would do it, since it has map and deref implementations:

```rust
#[derive(Debug, FromDeriveInput)]
struct DarlingTestDerive {
    ident: Ident,
    generics: Generics,
    data: darling::util::SpannedValue<darling::ast::Data<(), ()>>,
}
```

Unfortunately not:

```text
error[E0308]: `?` operator has incompatible types
  --> src/lib.rs:31:17
   |
31 | #[derive(Debug, FromDeriveInput)]
   |                 ^^^^^^^^^^^^^^^ expected struct `SpannedValue`, found enum `darling::ast::Data`
   |
   = note: `?` operator cannot convert from `darling::ast::Data<_, _>` to `SpannedValue<darling::ast::Data<(), ()>>`
   = note: expected struct `SpannedValue<darling::ast::Data<(), ()>>`
                found enum `darling::ast::Data<_, _>`
   = note: this error originates in the derive macro `FromDeriveInput` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I thought to try it as a separate field, eg.

```rust
#[derive(Debug, FromDeriveInput)]
struct DarlingTestDerive {
    ident: Ident,
    generics: Generics,
    data: darling::ast::Data<(), ()>,
    span: darling::util::SpannedValue<??>
}
```

...but as the question marks suggest, I have no idea what `T` should be there.

I also can't figure out how to obtain a span from any of Darling's types directly eg. I can easily do:

```rust
let Some(data @ Fields { .. }) = darling_test_derive.data.take_struct() else { ... };
```

or

```rust
let Some(Fields { style, fields, .. }) = darling_test_derive.data.take_struct() else { ... };
```

...but none of those types seem to have any way to extract a span.

Anyway, this seems like a documentation issue as much as anything else, so if you can point me in the right direction I'll try to make some notes as I go and open a PR with additional documentation eventually.

**Comment by detly** [comment]
> have you looked at using `#[darling(supports(struct_any))]`

Is this in the rustdocs, and if not, what source file is it in?

**Comment by TedDriggs** [comment]
Looks like it isn’t documented. Check out [this example](https://github.com/TedDriggs/darling/blob/master/examples/supports_struct.rs), and the implementation [here](https://github.com/TedDriggs/darling/blob/master/core/src/options/shape.rs)

**Comment by detly** [comment]
Ah that's neat! Is the intended usage to still use a `data: darling::ast::Data<Ignored, T>` field and do `take_struct().unwrap()`, or is there another type to use for the field?

**Comment by TedDriggs** [comment]
`Ignored` would be the way to go.

**Comment by detly** [comment]
> in essence you could write data: `darling::ast::Data<SpannedValue<...>>`

This was one of the points of confusion for me - `Data` takes two generics (enum variants and struct fields), should there be two `SpannedValue` types enclosing those types ie.

```rust
data: Data<SpannedValue<V>, SpannedValue<F>>
```

...or something else?

**Comment by TedDriggs** [comment]
Doing that would mean you’d have a spanned value for each variant, and a spanned value for each field. Which is fine, if that’s your goal.

**Comment by detly** [comment]
No, my goal is to have a span that covers all the fields ie. what syn and darling call the data.

**Comment by TedDriggs** [comment]
I don’t think there’s an easy way to do that.

**Comment by detly** [comment]
Ah nuts. It *is* possible to do by traversing the underlying syn types and getting the span for whatever kind of data you have in the type, but (a) you have to go pretty deep down the tree, and (b) you have to keep the input side by side with darling's structures. I was hoping for a neater way.

If I do manage to come up with something with a neater interface, would you be interested in doing that in darling somehow? I can't promise anything, but if I do it and it fits here, I can contribute it.

**Comment by TedDriggs** [comment]
I’d certainly be open to it. I think the problem you’ll have is that there’s not really a place to put the thing.

Did `#[darling(supports(…))]` help with your original problem, or does that have an issue that means it can’t be used?

**Comment by TedDriggs** [comment]
I think it’s wise to close this and file an issue for documentation, since that’s pretty far removed from this issue’s original stated topic.

**Comment by TedDriggs** [comment]
You could also check out WithOriginal as a way of keeping each field intact to fish the spans out - that won’t give you one span for the whole body, but it would give you the pieces needed for each field.

**Comment by detly** [comment]
Oh that's a great pointer, I'll have a look.

**Comment by detly** [comment]
One last thing (maybe):

> You could also check out WithOriginal as a way of keeping each field intact

Presumably I would replace `data: Data<(), MyField>` with `data: WithOriginal<Data<(), MyField>, O>` - what is `O` expected to be? `syn:::Data` doesn't work, I get a similar error to the `SpannedValue` (mis)use above:

```text

**Comment by detly** [comment]
Never mind, I figured it out! It implements `FromDeriveInput` already with a blanket impl over `T`, so `WithOriginal::<DarlingTestDerive, _>::from_derive_input(&input)?;` works beautifully.

**Comment by TedDriggs** [comment]
That works too! I was thinking you'd probably want to do something like this...

```rust
data: darling::ast::Data<Ignored, WithOriginal<MyField, syn::Field>>
```

That would give you access to the original fields with each of their span infos, so that when you have an error which impacts one or more of them you could add diagnostics to the right places instead of to the whole body. However, if you've found something that works for what you need, then party on!
