### ISSUE TITLE
Support for attrs of the same name?

### ISSUE THREAD

**Issue by TheDan64** [TedDriggs/darling#233]
Hi, I'd like to do something like `#[attr(a = foo, a = bar)]` where I can specify the same flag multiple times.

I figured you'd be able to do something like this:
```rust
#[derive(Debug, FromMeta)]
struct Args {
    pub a: Vec<Expr>,
}
```
But this doesn't compile: `Vec<syn::Expr>: FromMeta` is not satisfied

**Comment by TedDriggs** [comment]
Have you tried adding `#[darling(multiple)]` to the field?

**Comment by TheDan64** [comment]
Thank you! I didn't find this option in the docs. Is there any reason not to support this out of the box with Vec?

**Comment by TedDriggs** [comment]
Glad you're unblocked!

There are `FromMeta` impls for `Vec` which require the macro-user to only declare the field name once, and then allows them to pass a single meta that is parsed into a Vec.
