### ISSUE TITLE
Recognising generic types with `PathList`

### ISSUE THREAD

**Issue by wainwrightmark** [TedDriggs/darling#234]
Hi. I'm trying to use `PathList` in a `FromDeriveInput` struct. It works great for normal types but doesn't work for generic types.

My attribute looks like 

```rust
#[derive(FromDeriveInput, Default)]
#[darling(default, attributes(store))]
struct Opts {
    listener: PathList
}
```

and I'm parsing it with

```rust
let opts = Opts::from_derive_input(&input).expect("Invalid options");
```

It works fine for code like this

```rust
#[derive( Store)]
#[store(listener(MyListener1, MyListener2))]
struct State {
    count: u32,
}
```

but not for generic types

```rust
#[derive( Store)]
#[store(listener(HistoryListener::<State>))]
struct State {
    count: u32,
}
```
gives 

```
proc-macro derive panicked
message: Invalid options: Error { kind: Custom("expected path segment after `::`"), locations: ["listener"], span: Some(#0 bytes(156..157)) }
```

Doing it without the tubofish `#[store(listener(HistoryListener<State>))]` gives
```
proc-macro derive panicked
message: Invalid options: Error { kind: Custom("expected `,`"), locations: ["listener"], span: Some(#0 bytes(154..155)) }
```

Am I doing something wrong? Is there a way around this? Using `vec<Path>` with the `multiple` attribute does work but the syntax you have to pass in is different and I don't like it as much.

**Comment by TedDriggs** [comment]
The version without a turbofish is a `Type` but not a `Path`, so I’m not surprised to see an error from that one.

You could file a `syn` issue to see if there’s any appetite there for allowing non-ident parts in these paths, but unless the support is added there this will continue not to work in `darling`.

**Comment by TedDriggs** [comment]
One random idea for you - could you maybe make this field take a [`TypeTuple`](https://docs.rs/syn/latest/syn/struct.TypeTuple.html)? Then the syntax would be…

```rust
#[store(listener = (HistoryListener<State>, OtherListener<State>))]
```
