### ISSUE TITLE
Derive FromMeta on signed integer does not parse negative values 

### ISSUE THREAD

**Issue by greyblake** [TedDriggs/darling#244]
I guess I just discovered that `FromMeta` does not handle properly negative integers.

Example:

```rs
#[derive(Debug, FromMeta)]
struct ValidationRules {
    max: Option<i32>,

    min: Option<i32>,
}

// In expand
let items = NestedMeta::parse_meta_list(token_stream)?;

// This line fails
let validators = ValidationRules::from_list(&items)?;
/*
    Error {
        kind: UnexpectedType(
            "unary",
        ),
        locations: [
            "min",
        ],
        span: Some(
            #0 bytes(51..52),
        ),
    },
*/
```

Consuming code:

```rs
#[nutype(
    validate(min = -100, max = 100)
)]
#[derive(Debug)]
pub struct Amount(i32);
```

The output with an error:

```
error: Unexpected literal type `unary`
 --> dummy/src/main.rs:5:20
  |
5 |     validate(min = -100, max = 100)
  |                    ^

```

**Comment by TedDriggs** [comment]
This isn’t a `darling` bug - this is the behavior of Rust ([source](https://users.rust-lang.org/t/why-are-negative-value-literals-expressions/43333)).

**Comment by greyblake** [comment]
@TedDriggs I would disagree with the statement.

On the very low level, Rust indeed, sees `-100` as sequence of 2 tokens: `-` and `100`. And this is fine.
But IMHO, a library that provides parsing capabilities like darling should be able to "understand" these 2 tokens as a single integer value.

**Comment by TedDriggs** [comment]
`darling` has been burned in the past by attempting to go too far beyond what was supported by the underlying libraries - see the currently-open discussion about how to deal with the automatic reinterpretation of strings as expressions.

Here's an example of how you can do this without relying on native support from `darling`.

```rust
use std::ops::Neg;

use darling::{Error, FromDeriveInput, FromMeta, Result};
use quote::ToTokens;
use syn::Expr;

fn parse_negatable<T: FromMeta + Neg<Output = T>>(meta: &syn::Meta) -> Result<T> {
    if let syn::Meta::NameValue(nv) = meta {
        match &nv.value {
            Expr::Lit(v) => T::from_value(&v.lit),
            Expr::Unary(v) => {
                let syn::UnOp::Neg(_) = v.op else {
                    return Err(Error::unexpected_expr_type(&nv.value));
                };

                T::from_expr(&v.expr).map(Neg::neg)
            }
            _ => Err(Error::unexpected_expr_type(&nv.value)),
        }
    } else {
        T::from_meta(meta)
    }
}

#[derive(Debug, FromDeriveInput)]
#[darling(attributes(my_trait))]
pub struct MyInputReceiver {
    #[darling(default, with = parse_negatable, map = Some)]
    min: Option<i64>,

    #[darling(with = parse_negatable)]
    max: i64,
}

fn main() {
    let parsed = syn::parse_quote! {
        #[derive(MyTrait)]
        #[my_trait(min = -100, max = 1_000)]
        pub struct Foo;
    };
    let receiver = MyInputReceiver::from_derive_input(&parsed).unwrap();

    println!(
        r#"
INPUT:

{}

PARSED AS:

{:?}
    "#,
        parsed.into_token_stream(),
        receiver
    );
}
```

I admit that I could see some utility in having this on by default for numbers, but after the `Expr` issue I'm really wary of doing so in a way that could break people in future.

**Comment by TedDriggs** [comment]
@greyblake for the `nutype` use-case, do you specifically need the `min` and `max` values to be literals, or do you need `Expr` that can be used in `const` positions? Enabling only negative numbers would still leave a lot of other sensible inputs impossible, e.g. `max = MIN + ALLOWED_RANGE`.

**Comment by greyblake** [comment]
Thanks for the example.
Yeah, at the moment I tend to parse it manually with `syn::parse`.

At the moment `nutype` parses only literals, but I plan to extend it to support `Expr` / `TokenStream` as well for arbitrary things (e.g. constants).

One of the benefit of having integer literals parsed at compile time is ability to have extra validations
(e.g. check that `min <= max`)

**Comment by TedDriggs** [comment]
> At the moment nutype parses only literals, but I plan to extend it to support Expr / TokenStream as well for arbitrary things (e.g. constants).

I’m not sure I follow this; if the `min` and `max` attributes were of type `syn::Expr` then you could generate a `const MIN = …;` and `const MAX = …;` and use those in the validation. It also looks like you can use `panic` in const scenarios; I’m not sure what the resulting error span would be though.

**Comment by greyblake** [comment]
What I mean is that at the moment if you specify the validation like the following:

```rs
#[nutype(validate(min = 100, max = -100))]
pub struct Percentage(i8);
```

Nutype would detect at compile time, that given `max` is less than given `min`, and return an error:

```
error: `min` cannot be greater than `max`.
 --> src/main.rs:3:30
  |
3 | #[nutype(validate(min = 100, max = -100))]
  |                              ^^^
```

**Comment by TedDriggs** [comment]
Right, that makes sense. What I'm suggesting is that you could generate code like this:

```rust
struct Percentage(i18);

impl Percentage {
    const MIN: i8 = 25;
    const MAX: i8 = 20;

    pub fn new(value: i8) -> Result<Self, PercentageError> {
        // body elided 
    }
}

const _: () = assert!(
    Percentage::MAX > Percentage::MIN,
    "Percentage max must be greater than min"
);

fn main() {
    println!("{}", Example::MAX);
}
```

That would make it possible to use _any_ const expression for the `min` and `max`, and the assertion still gives you compile-time validation.

**Comment by greyblake** [comment]
@TedDriggs This is a very interesting trick, thank you! I haven't thought about it.
