### ISSUE TITLE
Specify the field value implicitly and explicitly

### ISSUE THREAD

**Issue by pintariching** [TedDriggs/darling#251]
```rust
struct A {
    #[validate(must_match(other = "val2"))]
    val: String,
    val2: String,
}

struct B {
    #[validate(must_match("val2"))]
    val: String,
    val2: String,
}

// A and B both get parsed to the same value
#[derive(FromMeta)]
struct MustMatch {
    other: Option<Expr>,
    // other fields
}
```

The attribute `other` can either be specified explicitly or implicitly without the `other =` and it gets mapped automatically to the `other` field. How could I do something like this with `darling`?

**Comment by TedDriggs** [comment]
You would need to write a custom parsing function for that, likely using `#[darling(with = path::to::fn)]`.
