### ISSUE TITLE
Enable `diagnostics` feature on Rust `stable`

### ISSUE THREAD

**Issue by pintariching** [TedDriggs/darling#253]
Currently the `diagnostics` feature works only  for `nightly`. Could it be made to work for `stable` too?

**Comment by TedDriggs** [comment]
I believe that enabling it for stable fails because it relies on rustc features that aren't stabilized.

**Comment by TedDriggs** [comment]
Closing this since I don't see a timeline for `diagnostics` hitting stable; if that does happen and you're later reading this, please either comment here or file a new issue.
