### ISSUE TITLE
panic from integer parsing

### ISSUE THREAD

**Issue by dimpolo** [TedDriggs/darling#289]
When parsing something like:
`number = 1000` into a `u8` I'm getting:
```
error: proc-macro derive panicked                                                                                                                                                  
    = help: message: called `Result::unwrap()` on an `Err` value: Error("number too large to fit in target type")
```

This presumably comes from this `unwrap`:
https://github.com/TedDriggs/darling/blob/78f3d11e76b5f63c47a453daa679956f1507af43/core/src/from_meta.rs#L231

Quoting from the docs:
> ... darling prefers not to fail on the first error it encounters, instead doing as much work as it can, accumulating errors into a single report.

It would be great to replace the `unwrap` with the usual error handling

**Comment by TedDriggs** [comment]
Agreed; that should be updated. Not sure why I currently have it panicking.
