### ISSUE TITLE
Is it possible to parse undeclared attributes while analyzing `syn` tree?

### ISSUE THREAD

**Issue by nyurik** [TedDriggs/darling#307]
I have a proc macro attached to a `fn` item.  On some of the function's attributes inside that mod I would like to have custom attribute that has associated proc macro attributes declared. This is similar to how `#[default]` can be attached to an enum value inside the `#[derive(Default)]`.  How can I do this, and would it be possible to document it somewhere?

### Example

```rust
/// Usage
#[my_proc_macro]
fn bar(
  #[arg(default = "value")] baz: &str
) {
  todo!()
}
```

```rust
/// Fill out this struct from the `#[arg(default = "baz")]`
#[derive(Default, Debug, FromMeta)]
#[darling(default)]
pub struct ArgConfig {
    pub default: Option<String>,
}


// Parsing
#[proc_macro_attribute]
pub fn my_proc_macro(args: pm::TokenStream, input: pm::TokenStream) -> pm::TokenStream {
    let fn_item = parse_macro_input!(input as ItemFn);
    for arg in &fn_item.sig.inputs {
      let FnArg::Typed(ty) = arg else { continue };
      // use ty.attrs -- parse into ArgConfig
      todo!();
   }
}
```

**Comment by TedDriggs** [comment]
I think you're looking for the [`FromAttributes`](https://docs.rs/darling/latest/darling/trait.FromAttributes.html) trait. `ArgConfig` would become:

```rust
#[derive(Default, Debug, FromAttributes)]
#[darling(attributes(arg), default)]
pub struct ArgConfig {
    pub default: Option<String>
}
```

You could then use [`darling::util::WithOriginal`](https://docs.rs/darling/latest/darling/util/struct.WithOriginal.html) to store both the `FnArg` and the `ArgConfig` in one struct.
