### ISSUE TITLE
Update version on crates.io

### ISSUE THREAD

**Issue by ennis** [TedDriggs/darling#43]
It seems that the version on crates.io is still at 0.6.3 which does not work with syn 0.14 and quote 0.6. Would it be possible to push a 0.7 on crates.io? 
(Related to issue #38)

**Comment by TedDriggs** [comment]
Yes; I'll take a look at publishing tomorrow; I want to make sure I haven't left things in a weird state since it's been a couple weeks.

**Comment by TedDriggs** [comment]
Sorry for the silence on this; publishing now.
