### ISSUE TITLE
Add #[darling(word)] for enum variants

### ISSUE THREAD

**Issue by TedDriggs** [TedDriggs/darling#63]
`DefaultExpression` is one example of an enum that wants to map a specific variant to the appearance of the field ident with no associated value. This would only be valid on variants in `FromMeta`. The variant must be a unit variant.

**Comment by TedDriggs** [comment]
@chipsenkbeil I think this is what you're looking for `ent(field)`

**Comment by chipsenkbeil** [comment]
In my case, I'm looking for a word or a list as the attribute can be `#[ent(field)]` if just marking a struct field as an *entity field*, or something like `#[ent(field(indexed, mutable))]` if marking as an entity field with special flags.

Separately, I also have `#[ent(edge)]` that can have `#[ent(edge(type = "some::type", policy = "SomeEnumVariant"))]`.

To summarize, I'm both looking for the presence of `field` or `edge` as a boolean indicator as well as optional inner words/named values to assign other properties. All of the inner content comes across as optional, with words defaulting to false as booleans and types defaulting to None/a default value.

**Comment by TedDriggs** [comment]
Check out `darling::util::Override`. The naming isn't the most obvious for your use-case, but I believe it does what you're looking for.

**Comment by TedDriggs** [comment]
Given the existence of the above workaround (and the lack of movement for almost 3 years), I'm closing this as "Won't Fix."
