### ISSUE TITLE
Include LICENSE into sub-crates

### ISSUE THREAD

**Issue by ignatenkobrain** [TedDriggs/darling#64]
We need that in order to package darling_* for Fedora.

Thanks in advance!

**Comment by TedDriggs** [comment]
Is a sym-link sufficient?

**Comment by TedDriggs** [comment]
v0.8.6 is live with this change and the `exclude` change.

**Comment by ignatenkobrain** [comment]
Thanks!

**Comment by TedDriggs** [comment]
What version of rustc are you planning to use? I'd like to enable the `suggestions` feature by default in v0.9.0, so people using these proc-macros get "did you mean ___" messages when they misspell fields in attributes, but doing so would require bumping the min rustc version up.

**Comment by ignatenkobrain** [comment]
We always ship latest rustc in Fedora/EPEL, so we don't care much :)

**Comment by TedDriggs** [comment]
Sweet. Mind if I ask what you're planning to use the crate for? Always interested to hear when it's solving real-world problems.

**Comment by ignatenkobrain** [comment]
I'm just a packager of Rust stuff in Fedora. And darling is in dependency chain of [ffsend](https://github.com/timvisee/ffsend)
