### ISSUE TITLE
Optional fields in FromMeta impl derive parsing 

### ISSUE THREAD

**Issue by nishtahir** [TedDriggs/darling#75]
Is there a way to have optional fields in a struct be optional when parsing? In my example, 

``` rust
#[derive(Debug, FromMeta)]
struct Attrs {
    path: String,
    data: Option<String>,
}
```

``` rust
let attrs = Attrs::from_meta(&meta)?;

// parses correctly with
#[my_macro(path = "../../", data = "something")]
// But fails to parse with 
#[my_macro(path = "../../")]
```

**Comment by azdle** [comment]
@nishtahir it seems you need to add `#[darling(default)]` to allow any `Option` typed field to default to `None`.

(Not an expert on this crate by any means, just my observation while trying to use it myself.)

**Comment by TedDriggs** [comment]
@azdle is correct; setting the field to be defaulted is the way to go here. You can also set the whole struct to be defaulted if you prefer.
