### ISSUE TITLE
Unnamed attributes

### ISSUE THREAD

**Issue by MaikKlein** [TedDriggs/darling#76]
```
#[derive(Foo)]
#[response(Bar)]
struct Baz;
```
Can this currently be expressed in darling? I tired to do the following: 

```
#[derive(FromDeriveInput)]
#[darling(attributes(response))]
struct RequestAttrs(Ident);
```
```
    |
    | #[derive(FromDeriveInput)]
    |          ^^^^^^^^^^^^^^^ the trait `darling_core::from_derive_input::FromDeriveInput` is not implemented for `proc_macro2::Ident`
    |
    = note: required by `darling_core::from_derive_input::FromDeriveInput::from_derive_input`

```

**Comment by TedDriggs** [comment]
Have you tried using `darling::util::IdentList`?

That doesn't automatically limit to one, but you could check the length yourself.

**Comment by tarcieri** [comment]
It seems `darling::util::IdentList` no longer exists?

I can detail the use cases I'd like to support if that helps. I'd like to have support for the following:

```
#[myattr(foo, key1 = "...", key2 = "...", key3 = 42)]
#[myattr(bar, key1 = "...", key2 = "...", key3 = 42)]
```

and ideally also be able to support this:

```
#[myattr(baz(foo), key1 = "...", key2 = "...", key3 = 42)]
#[myattr(baz(bar), key1 = "...", key2 = "...", key3 = 42)]
```

Happy to accomplish that in whatever way works (e.g. manually parse the first attribute argument, and then use the custom derive for `key1`...`keyN` name/value pairs)

**Comment by TedDriggs** [comment]
Just saw this; looking at it now.

**Comment by tarcieri** [comment]
For what it's worth, I just ended up going with a key/value syntax across the board which ended up being fine

**Comment by TedDriggs** [comment]
It looks like `IdentList` was changed to `PathList` but is otherwise equivalent. I think your use-case should work just fine:

```rust
struct AttrThings {
    baz: PathList,
    key1: String,
    key2: String,
    // ...
}
```

Let me know if it has problems and I'll be happy to help out.
