### ISSUE TITLE
`Error::with_span()` should have a form that takes just a `Span`

### ISSUE THREAD

**Issue by nrxus** [TedDriggs/darling#90]
While having `Error::with_span()` take any `T: Spanned` is pretty useful, sometimes all I have is a `Span` and it would be more ergonomic to pass in that span itself rather than make a wrapper around `Span` that implements `Spanned`.

**Comment by TedDriggs** [comment]
Can you provide an example? I’ve generally found that callers should think about hanging the error off a particular AST element rather than an arbitrary span, so I’m curious how you ended up in this situation.

**Comment by nrxus** [comment]
It's slightly convoluted but essentially I parse through the signature of some method and store only the needed data out of it, this does not include the receiver itself, but rather just a tag of what kind of receiver it was (i.e., `&self` vs `self: Rc<Self>`. I do not store the actual data due to lifetime and mutability constraints since I am also mutating the other arguments as I go through this procedure, and I also do not need the actual receiver, I just need to know that it existed, and which kind if was. I would like to then in a different part of my macro expansion verify that the receiver type fits some criteria, and if it doesn't error out. However I did not store the actual receiver, since I did not need it, and having it would have created lifetime problems so I can't pass that `FnArg` to `with_span`. I could clone `FnArg` to avoid any lifetime issues but the only part of it I need is the Span and only for errors so cloning it all the time feels like a waste. 

Curently I am making a dumb struct `SpanMarker` that wraps a `Span` and implements `Spanned` but it feels hacky. 

A method that just takes a span would also mirror [`syn::Error::new`](https://docs.rs/syn/1.0.14/syn/struct.Error.html#method.new) slightly more.

**Comment by TedDriggs** [comment]
> Curently I am making a dumb struct `SpanMarker` that wraps a `Span` and implements Spanned but it feels hacky.

This isn't much better, but you can replace your own struct with [`darling::util::SpannedValue<()>`](https://docs.rs/darling/0.10.2/darling/util/struct.SpannedValue.html).

Is this still a friction point for you/can you point me to the code in `faux` where this is an issue?

**Comment by TedDriggs** [comment]
Given that `SpannedValue` exists, I'm inclined to close this.

**Comment by TedDriggs** [comment]
@nrxus turns out that `Span` impls `Spanned` 🤦 don't know why I didn't think to check that. So you don't even need to use `SpannedValue`
