### ISSUE TITLE
Support for Alpine

### ISSUE THREAD

**Issue by ghost** [TedDriggs/darling#94]
I am trying to install a cargo binary (cargo-watch) in an Alpine Docker image, but it won't compile because darling_macro does not support Alpine targets.

```
error: failed to compile `cargo-watch v7.3.0`, intermediate artifacts can be found at `/tmp/cargo-installp8c4VF`

Caused by:
  cannot produce proc-macro for `darling_macro v0.10.2` as the target `x86_64-unknown-linux-musl` does not support these crate types
```

**Comment by TedDriggs** [comment]
`darling_macro` is just the proc-macro wrapper, so I'm not sure what I'd need to (or be able to) change to add support for Alpine. However, if you find out a way to make this work I'll be happy to hook it up.

**Comment by hdf1986** [comment]
Hi! Im just starting with Rust so i may not be too in context, but i tried to install cargo-watch in docker alpine and ran into this same issue.

After some research i found this comment https://github.com/hound-search/hound/issues/238#issuecomment-336915272 which helped me to solve the issue.

```bash
apk add --no-cache musl-dev
```
