### ISSUE TITLE
 Nested proc attributes

### ISSUE THREAD

**Issue by SirWindfield** [TedDriggs/darling#95]
Is `darling` currently capable of somehow parsing the following?
```rust
#[derive(Debug)]
pub struct SomeName {
    #[attr1(
        attr2("hello"),
        attr2("world")
    )]
    some_arg: String,
}
```

As far as I could tell using `Vec` doesn't work right now. And I know of at least one crate who does implement vector-likes using the above syntax (but without the convenience of darling).

The goal is to somehow b able to parse multiple values to a single argument, preferable as `Vec<String>`.

**Comment by TedDriggs** [comment]
So in your example, you have `attr2(...)` repeating under the same parent. That's a bit odd - if `attr2` has multiple values, `darling` would be fine with this:

```rust
#[derive(Debug)]
pub struct SomeName {
    #[attr1(attr2("hello", "world"))]
    some_arg: String,
}
```

That would deserialize into this:

```rust
#[derive(FromMeta)]
struct Foo {
    attr2: Vec<String>
}
```

Similarly, if the input was:

```rust
#[derive(Debug)]
pub struct SomeName {
    #[attr1(
        attr2("hello"),
        attr3("world") // notice the field name has changed
    )]
    some_arg: String,
}
```

Then that would deserialize happily into:

```rust
#[derive(FromMeta)]
struct Foo {
    attr2: String,
    attr3: String,
}
```

And those structs nest as deep as you want to go.

For your original case, I'd need to think about that a bit more. I believe you could make `attr1`'s field type be some `syn` type so that you could use the rest of `darling` and just handle this one piece specially yourself, but that's not super-ergonomic.

Can you provide a bit more detail on why you've chosen this particular construction?

**Comment by SirWindfield** [comment]
@TedDriggs Sure thing! I originally wanted just an attribute that takes multiple values as a key, e.g.:

```rust
#[derive(Debug)]
pub struct SomeName {
    #[attr(methods = ["value1", "value2"])]
    some_arg: String,
}
```

I couldn't get this to work correctly. Using your first approach actually resulted in compilation errors for me:

```
error[E0277]: the trait bound `std::vec::Vec<MethodArg>: darling::FromMeta` is not satisfied
  --> standalone\method-delegate\src\lib.rs:12:17
   |
12 | #[derive(Debug, FromMeta)]
   |                 ^^^^^^^^ the trait `darling::FromMeta` is not implemented for `std::vec::Vec<MethodArg>`
   |
   = help: the following implementations were found:
             <std::vec::Vec<syn::generics::WherePredicate> as darling::FromMeta>
   = note: required by `darling::FromMeta::from_meta`

error: aborting due to previous error
```

Given the following Rust code:
```
extern crate method_delegate;

#[derive(FromMeta)]
pub struct Delegate {
    delegate: Vec<String>,
}

pub struct Config {
    #[delegate("method_1", "method_2")]
    methods: String,
}

fn main() {
    let _config = Config;
}
```

**Comment by thedodd** [comment]
Maybe just adding a blanket `impl<T> FromMeta for Vec<T> where T: FromMeta {}` would be a decent start. In such a case, I would imagine a case where the end user would be specifying the same derive helper attribute multiple times in the same attribute or perhaps in separate sibling attrs, like:

```rust
#[derive(FromField)]
pub struct FromFieldModel {
    pub ident: Option<syn::Ident>,
    pub ty: syn::Type,
    pub attrs: Vec<syn::Attribute>,
    pub custom_attr: Vec<CustomAttrModel>,
}

#[derive(FromMeta)]
pub struct FromMetaModel {
    attr_field0: String,
    attr_field1: u64,
    // ... etc
}

// End User Code

#[derive(VecExample)]
struct EndUserType {
    #[custom_attr(attr_field0="abc", attr_field1=123)]
    #[custom_attr(attr_field0="xyz", attr_field1=789)]
    field0: String,
}
```

In the above example, the attrs specified on the `EndUserType.field0` would be collected into the `FromFieldModel.custom_attr` vec. This should also support the use case being discussed above by @SirWindfield, given that `String` already implements `FromMeta`.

**Comment by SirWindfield** [comment]
If the goal is to define multiple values for one single key, I don't think that your example is ergonomic enough @thedodd. Just as an example, I wanted to have around 10-ish values passed to it. Repeating the same line 10 times reduces code clarity and just clutters the struct definition too much in my opinion.

On the other side, I am not even sure if `#[custom_attr(value = [])]` can be done due ot the square brackets. I guess it is possible, the impl of `FromMeta` would just parse them as an array.

**Comment by thedodd** [comment]
> I don't think that your example is ergonomic enough

lol ok. Well, that is why I also mentioned: "the end user would be specifying the same derive helper attribute multiple times in the same attribute or perhaps in separate sibling attrs" ... so, I mean there are only so many options. However, this is totally beside the point.

My concern is about being able to specify some sort of repetition of structures.

**Comment by TedDriggs** [comment]
@thedodd there was a draft of what you're describing in #72, but we couldn't figure out a use-case for an ordered collection of something that was more complex than identifiers.

@SirWindfield I'm 99% sure you can do this with a custom `FromMeta` implementation for your use-case, but you will need to test if `syn` is happy with square brackets in the meta item. I'm going to try a couple things on my end, but my availability has been pretty constricted the last few weeks. I wouldn't suggest waiting on me getting the opportunity to dive in deeply if you need to keep moving on your project. If you're able to find a workable solution I'd love to see it.

An alternative implementation would be to use `HashMap` to accumulate the items that should be in your list, and to then use `PathList` to have the caller provide the order. It's slightly less convenient, but it's better than multiple attributes.

**Comment by TedDriggs** [comment]
So I forgot that this already works using the `multiple` flag. See below for an example.

```rust
use darling::{FromDeriveInput, FromMeta};

#[derive(Debug, FromMeta, PartialEq, Eq)]
struct Command {
    condition: String,
    action: String,
}

impl From<(&'static str, &'static str)> for Command {
    fn from((condition, action): (&'static str, &'static str)) -> Self {
        Self {
            condition: condition.to_string(),
            action: action.to_string(),
        }
    }
}

#[derive(FromDeriveInput)]
#[darling(attributes(hello))]
struct Lorem {
    #[darling(multiple, rename = "command")]
    commands: Vec<Command>,
}

#[test]
fn expand_many() {
    let di = syn::parse_quote! {
        #[hello(
            command(condition = "true", action = "start::the::thing"),
            command(condition = "this_works", action = "start::next::thing")
        )]
        pub struct Baz;
    };

    let lorem: Lorem = Lorem::from_derive_input(&di).unwrap();
    assert_eq!(
        lorem.commands,
        vec![
            ("true", "start::the::thing").into(),
            ("this_works", "start::next::thing").into(),
        ]
    );
}
```
