### ISSUE TITLE
Pass unquoted Ident to FromMeta

### ISSUE THREAD

**Issue by oberien** [TedDriggs/darling#99]
Is it possible to pass an unquoted identifier as a Meta? I'd like to have something like this:

```rust
#[derive(Foo)]
#[commands(
    command(struct = Command1, name = "command_1"),
    command(struct = Command2, name = "command_2")
)]
struct Bar;

struct Command1;
impl Command for Command1 { … }
struct Command2;
impl Command for Command2 { … }
```

I've tried the following:

```rust
#[derive(FromMeta)]
struct Command {
    #[darling(rename = "struct")]
    struct_ident: Ident, // should be Command1 / Command2
    name: String, // should be "command_1" / "command_2"
}

struct Foo {
    ident: Ident, // should be Bar
    commands: Vec<Command>,
}
```

The `Vec<Command>` depends on #95 and would be an actual use-case where #72 would be needed. However, if I just say `commands: Command` and only have `#[commands(command(struct = Command1, name = "command_1"))]` it also doesn't work, because from what I understand darling doesn't support literals in attributes and always expects a bool, a number, or a quoted string (at least that's what `FromMeta::from_*` offers).

Is there a way currently in darling which I could use to parse the above?

NB: Initially I had the following syntax, which also doesn't seem to be supported by darling. However, I feel like that is less intuitive, which is why I switched to the one above.

```rust
#[derive(Foo)]
#[commands(Command1 = "command_1", Command2 = "command_2")]
struct Bar;
```

**Comment by TedDriggs** [comment]
Was the issue in the second syntax that you were trying to allow _n_ `CommandX` meta items?

I'm not sure an unquoted `Ident` is valid Rust in that position. The way `serde` handles this is that you'd write `struct = "Command1"` though I'd be surprised if _that_ works because I think `struct` might be a reserved keyword even inside an attribute.

Let's discuss the vector over on #72

**Comment by TedDriggs** [comment]
This works apart from requiring quotation marks. I don't think it's worth deviating from idiomatic Rust to support removing the quotation marks around the struct identifier, especially since that would add a lot of complexity for structs that had type parameters or lifetimes.

```rust
use darling::{FromDeriveInput, FromMeta};

#[derive(Debug, FromMeta, PartialEq, Eq)]
struct Command {
    #[darling(rename = "struct")]
    struct_ident: String,
    name: String,
}

impl From<(&'static str, &'static str)> for Command {
    fn from((condition, action): (&'static str, &'static str)) -> Self {
        Self {
            condition: condition.to_string(),
            action: action.to_string(),
        }
    }
}

#[derive(FromDeriveInput)]
#[darling(attributes(hello))]
struct Lorem {
    #[darling(multiple, rename = "command")]
    commands: Vec<Command>,
}

#[test]
fn expand_many() {
    let di = syn::parse_quote! {
        #[hello(
            command(struct = "Command1", name = "foo"),
            command(struct = "Command2", name = "bar")
        )]
        pub struct Baz;
    };

    let lorem: Lorem = Lorem::from_derive_input(&di).unwrap();
    assert_eq!(
        lorem.commands,
        vec![
            ("Command1", "foo").into(),
            ("Command2", "bar").into(),
        ]
    );
}
```
